# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20160526_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='screenshot',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
